### ISSUE TITLE
Use `$x = $x;` before `let mut $x = $x;` in `pin_mut!`

### ISSUE THREAD

**Issue by zroug** [rust-lang/pin-utils#11]
In its current form `pin_mut!` creates a mutable reference to a variable that wasn't declared as mutable from the callers perspective.

Using `$x = $x;` before `let mut $x = $x;` would force the caller to declare `$x` as mutable.

I think that would be more consistent with how one would take a normal mutable reference.

**Comment by cramertj** [comment]
IMO the use of `mut` in `pin_mut` is the bit that should clarify this, similar to if the user wrote `let mut x = x;` (which is effectively what this is). I believe the semantics should stay as-is.

**Comment by zroug** [comment]
Okay. But wouldn't the same argument apply to
```
let mut x = 42;
let x = &mut x;
```
?

In this example the `mut` in `&mut` is similar to the `mut` in `pin_mut!` but the `mut` in `let mut x = 42;` is necessary nonetheless.

But I understand that one could argue differently here, because there is no second assignment.
