### ISSUE TITLE
Move on to semver major.minor.patch and off -alpha

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/pin-utils#27]
This library hasn't seen any updates since June, and new libraries such as `pin-project` and `pin-project-lite` have since sprung up, rounding out the library space around pinning.

I'd like to propose we move off the `-alpha` prefix, and to a less volatile release channel, because `-alpha` versions will *always* be updated by Cargo which isn't great. In fact, I'd like to propose we move this library to semver `major-minor-path` so changes can be more accurately communicated, which seems desirable for a library that's underpinning (heh) the entire async ecosystem.

I hope this makes sense. Thanks!

**Comment by Nemo157** [comment]
See #26 moving to `0.1.0`.

**Comment by cramertj** [comment]
Fixed in https://github.com/rust-lang-nursery/pin-utils/pull/26, releasing now.
