### ISSUE TITLE
cargo doc failing

### ISSUE THREAD

**Issue by carado** [rust-lang/pin-utils#36]
Hi!
While running `cargo doc` in a project which (indirectly) depends on `pin-utils`, I noticed that I encountered an error during the documentation of pin-utils 0.1.0.
The issue can be reproduced in a standalone project with pin-utils as its only dependency.
```
~/tmp/rust33 $ cargo init
     Created binary (application) package
~/tmp/rust33 $ echo 'pin-utils = "0.1.0"' >> Cargo.toml
~/tmp/rust33 $ cargo doc
    Updating crates.io index
 Documenting pin-utils v0.1.0
    Checking pin-utils v0.1.0
error[E0658]: linking to associated items of raw pointers is experimental
  --> /home/carado/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/metadata.rs:51:23
   |
51 | /// [`to_raw_parts`]: *const::to_raw_parts
   |                       ^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #80896 <https://github.com/rust-lang/rust/issues/80896> for more information
   = help: add `#![feature(intra_doc_pointers)]` to the crate attributes to enable
   = note: rustdoc does not allow disambiguating between `*const` and `*mut`, and pointers are unstable until it does

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not document `pin-utils`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name pin_utils /home/carado/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-utils-0.1.0/src/lib.rs --cap-lints allow -o /home/carado/tmp/rust33/target/doc --error-format=json --json=diagnostic-rendered-ansi -L dependency=/home/carado/tmp/rust33/target/debug/deps --crate-version 0.1.0` (exit code: 1)
~/tmp/rust33 $ cargo --version
cargo 1.51.0-nightly (ab64d1393 2021-02-10)
~/tmp/rust33 $ rustc --version
rustc 1.52.0-nightly (0148b971c 2021-02-18)
~/tmp/rust33 $ rustdoc --version
rustdoc 1.52.0-nightly (0148b971c 2021-02-18)
```

**Comment by taiki-e** [comment]
> ```
> error[E0658]: linking to associated items of raw pointers is experimental
>   --> /home/carado/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/metadata.rs:51:23
>    |
> 51 | /// [`to_raw_parts`]: *const::to_raw_parts
>    |                       ^^^^^^^^^^^^^^^^^^^^
>    |
>    = note: see issue #80896 <https://github.com/rust-lang/rust/issues/80896> for more information
>    = help: add `#![feature(intra_doc_pointers)]` to the crate attributes to enable
>    = note: rustdoc does not allow disambiguating between `*const` and `*mut`, and pointers are unstable until it does
> ```

The problem seems to be occurring in `core::ptr`, and unrelated to pin-utils. cc @Nemo157

maybe related to https://github.com/rust-lang/rust/pull/81172

**Comment by Nemo157** [comment]
Looks like https://github.com/rust-lang/rust/issues/82284

**Comment by taiki-e** [comment]
closing in favor of the upstream issue.
